/* Navarang menu data — edit prices/items here; the page renders from this object. */
var MENU_DATA = {
  "egg-curries": [
    { name: "Egg Burji", price: 100, veg: false },
    { name: "Egg Keema", price: 100, veg: false },
    { name: "Egg Curry", price: 100, veg: false },
    { name: "Egg Fry", price: 120, veg: false },
    { name: "Egg Roast", price: 120, veg: false },
    { name: "Egg Chilli", price: 120, veg: false },
    { name: "Egg Dal", price: 120, veg: false },
    { name: "Egg Tamata", price: 120, veg: false },
    { name: "Omlete", price: 60, veg: false },
    { name: "Egg Manchuria", price: 130, veg: false }
  ],
  "non-veg-starter": [
    { name: "Chicken Bone Fry", price: 180, veg: false },
    { name: "Chicken Bone Roast", price: 200, veg: false },
    { name: "Chicken Boneless Fry", price: 230, veg: false },
    { name: "Chicken Boneless Roast", price: 230, veg: false },
    { name: "Chili Chicken", price: 200, veg: false },
    { name: "Pepper Chicken", price: 230, veg: false },
    { name: "Chicken 65", price: 250, veg: false },
    { name: "Chicken Manchuria", price: 250, veg: false },
    { name: "Lollipop Roast", price: 250, veg: false },
    { name: "Lollipop Fry", price: 250, veg: false },
    { name: "Tiger Chicken", price: 270, veg: false },
    { name: "Lemon Chicken", price: 250, veg: false }
  ],
  "veg-curries": [
    { name: "Tamata Curry", price: 100, veg: true },
    { name: "Dal Curry", price: 100, veg: true },
    { name: "Batani Curry", price: 100, veg: true },
    { name: "Palak Curry", price: 100, veg: true },
    { name: "Dal Tadka", price: 120, veg: true },
    { name: "Veg Mix Curry", price: 120, veg: true },
    { name: "Mushroom Curry", price: 150, veg: true },
    { name: "Paneer Butter Masala", price: 180, veg: true },
    { name: "Palak Paneer", price: 160, veg: true },
    { name: "Kaju Tamata", price: 160, veg: true },
    { name: "Kaju Curry", price: 180, veg: true },
    { name: "Methi Chaman", price: 180, veg: true },
    { name: "Kaju Paneer", price: 200, veg: true }
  ],
  "veg-starters": [
    { name: "Batani Fry", price: 120, veg: true },
    { name: "Batani Roast", price: 120, veg: true },
    { name: "Groundnut Masala", price: 120, veg: true },
    { name: "Chena Fry", price: 120, veg: true },
    { name: "Gobi Fry", price: 120, veg: true },
    { name: "Gobi Manchuria", price: 140, veg: true },
    { name: "Onion Pakodi", price: 120, veg: true },
    { name: "Mushroom Fry", price: 150, veg: true },
    { name: "Mushroom Chili", price: 160, veg: true },
    { name: "Paneer Fry", price: 180, veg: true },
    { name: "Kaju Fry", price: 230, veg: true },
    { name: "Kaju Roast", price: 230, veg: true },
    { name: "Alasandha Fry", price: 120, veg: true },
    { name: "Paneer Manchuria", price: 200, veg: true },
    { name: "Paneer 65", price: 180, veg: true },
    { name: "Paneer Chilli", price: 200, veg: true },
    { name: "Mushroom Manchuria", price: 150, veg: true },
    { name: "Mushroom Pepper", price: 160, veg: true }
  ],
  "biryani": [
    { name: "Dum Biryani", price: 150, veg: false },
    { name: "Fry Biryani", price: 170, veg: false },
    { name: "SP Biryani", price: 200, veg: false },
    { name: "Mutton Fry Biryani", price: 350, veg: false },
    { name: "Natukodi Fry Biryani", price: 300, veg: false },
    { name: "Prawns Fry Biryani", price: 300, veg: false }
  ],
  "roti": [
    { name: "Ponga Roti", price: 8, veg: true },
    { name: "Patala Roti", price: 7, veg: true },
    { name: "Katak Roti", price: 7, veg: true }
  ],
  "fried-rice": [
    { name: "Egg Rice", price: 100, veg: false },
    { name: "Veg Rice", price: 100, veg: true },
    { name: "Chicken Rice", price: 120, veg: false },
    { name: "Jeera Rice", price: 120, veg: true },
    { name: "Gobi Rice", price: 120, veg: true },
    { name: "Mushroom Rice", price: 130, veg: true },
    { name: "Kaju Rice", price: 160, veg: true },
    { name: "Paneer Rice", price: 160, veg: true },
    { name: "Plain White Rice", price: 50, veg: true },
    { name: "Curd Rice", price: 60, veg: true }
  ],
  "chicken-curries": [
    { name: "Chicken Bone Curry", price: 170, veg: false },
    { name: "Chicken Boneless Curry", price: 230, veg: false },
    { name: "Butter Chicken", price: 250, veg: false },
    { name: "Kadai Chicken", price: 260, veg: false },
    { name: "Kaju Chicken", price: 270, veg: false },
    { name: "Mughlai Chicken", price: 270, veg: false },
    { name: "Lollipop Curry", price: 250, veg: false },
    { name: "Rambha Chicken", price: 270, veg: false },
    { name: "Panjabi Chicken", price: 270, veg: false },
    { name: "Andhra Chicken", price: 350, veg: false },
    { name: "Nellore Chicken", price: 350, veg: false },
    { name: "Bonda Chicken", price: 400, veg: false },
    { name: "Star Chicken", price: 250, veg: false },
    { name: "Fish Curry (2 pc)", price: 130, veg: false },
    { name: "Fish Fry (2 pc)", price: 130, veg: false },
    { name: "Prawns Curry", price: 270, veg: false },
    { name: "Prawns Fry", price: 280, veg: false },
    { name: "Natukodi Curry", price: 300, veg: false },
    { name: "Natukodi Fry", price: 300, veg: false },
    { name: "Mutton Curry", price: 320, veg: false },
    { name: "Mutton Fry", price: 350, veg: false },
    { name: "Crab Curry", price: 200, veg: false },
    { name: "Crab Roast", price: 200, veg: false },
    { name: "Kamju Curry (2 pc)", price: 240, veg: false },
    { name: "Kamju Roast (2 pc)", price: 250, veg: false }
  ],
  "specials": [
    { name: "Kheer", price: 50, veg: true },
    { name: "Badam Milk", price: 50, veg: true },
    { name: "Ice Cream", price: null, veg: true },
    { name: "Cool Drinks", price: null, veg: true }
  ]
};

/* Category display order, titles and icons — shared by the printed menu and the order app. */
var CATEGORY_META = [
  { id: "egg-curries", title: "Egg Curries", short: "Egg Curries",
    icon: '<path d="M32 8C20 8 12 26 12 38a20 20 0 0040 0C52 26 44 8 32 8z"/>' },
  { id: "non-veg-starter", title: "Non-Veg Starter", short: "Starters",
    icon: '<path d="M44 12c8 4 11 14 6 21-4 6-11 9-18 8-4-1-7 1-9 4l-6 9"/><path d="M17 54l-6 4M17 54l1 7M17 54l6 3"/>' },
  { id: "veg-curries", title: "Veg Curries", short: "Veg Curries",
    icon: '<path d="M10 32h44a22 22 0 01-44 0z"/><path d="M24 30c0-6 2-9 2-9M32 30c0-8 3-11 3-11M40 30c0-6 2-9 2-9"/>' },
  { id: "veg-starters", title: "Veg Starters", short: "Veg Starters",
    icon: '<path d="M32 6c6 10-4 12-4 20 0 4 3 7 7 7s8-4 8-9c6 4 9 11 9 17 0 13-11 23-24 23S8 54 8 41c0-9 5-16 9-21 2 8 7 10 7 10-2-9 2-16 8-24z"/>' },
  { id: "biryani", title: "Biryani", short: "Biryani",
    icon: '<path d="M14 30h36l-3 20a6 6 0 01-6 5H23a6 6 0 01-6-5z"/><path d="M10 30h44"/><path d="M22 30v-8a10 10 0 0120 0v8"/><circle cx="32" cy="12" r="3"/>' },
  { id: "roti", title: "Roti", short: "Roti",
    icon: '<circle cx="32" cy="32" r="21"/><path d="M32 15v10M32 39v10M15 32h10M39 32h10M21 21l7 7M36 36l7 7M43 21l-7 7M28 36l-7 7"/>' },
  { id: "fried-rice", title: "Fried Rice", short: "Fried Rice",
    icon: '<path d="M10 32h44a22 22 0 01-44 0z"/><circle cx="24" cy="25" r="1.6" fill="currentColor" stroke="none"/><circle cx="32" cy="21" r="1.6" fill="currentColor" stroke="none"/><circle cx="40" cy="25" r="1.6" fill="currentColor" stroke="none"/><circle cx="28" cy="29" r="1.6" fill="currentColor" stroke="none"/><circle cx="36" cy="29" r="1.6" fill="currentColor" stroke="none"/>' },
  { id: "chicken-curries", title: "Chicken, Mutton & Seafood Curries", short: "Chicken & Mutton",
    icon: '<path d="M10 32h44a22 22 0 01-44 0z"/><path d="M24 30c0-6 2-9 2-9M32 30c0-8 3-11 3-11M40 30c0-6 2-9 2-9"/>' },
  { id: "specials", title: "Navarang Specials", short: "Specials",
    icon: '<path d="M32 6l7 16 17 2-13 12 4 18-15-9-15 9 4-18-13-12 17-2z"/>' }
];
