/* Navrang menu data — edit prices/items here; the page renders from this object. */
var MENU_DATA = {
  "egg-curries": [
    { id: 1, name: "Egg Burji", nameTe: "గుడ్డు బుర్జీ", price: 110, veg: false, thumb: "images/menu/egg-burji-100.jpg", photo: "images/menu/egg-burji-500.jpg", top: true, ingredients: ["Eggs", "Onion", "Tomato", "Green Chili", "Ginger-Garlic", "Turmeric", "Coriander Leaves"], ingredientsTe: ["గుడ్లు", "ఉల్లిపాయ", "టమాట", "పచ్చిమిర్చి", "అల్లం-వెల్లుల్లి", "పసుపు", "కొత్తిమీర"], status: "Active", weeklyDishInd: false },
    { id: 2, name: "Egg Chilli", nameTe: "గుడ్డు చిల్లీ", price: 130, veg: false, status: "Active", weeklyDishInd: false },
    { id: 3, name: "Egg Curry", nameTe: "గుడ్డు కర్రీ", price: 110, veg: false, thumb: "images/menu/egg-currey-100.jpg", photo: "images/menu/egg-currey-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 4, name: "Egg Dal", nameTe: "గుడ్డు దాల్", price: 130, veg: false, status: "Active", weeklyDishInd: false },
    { id: 5, name: "Egg Fry", nameTe: "గుడ్డు ఫ్రై", price: 130, veg: false, status: "Active", weeklyDishInd: false },
    { id: 6, name: "Egg Keema", nameTe: "గుడ్డు కీమా", price: 110, veg: false, thumb: "images/menu/egg-keema-100.jpg", photo: "images/menu/egg-keema-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 7, name: "Egg Manchuria", nameTe: "గుడ్డు మంచూరియా", price: 140, veg: false, status: "Active", weeklyDishInd: false },
    { id: 8, name: "Egg Roast", nameTe: "గుడ్డు రోస్ట్", price: 130, veg: false, thumb: "images/menu/egg-roast-100.jpg", photo: "images/menu/egg-roast-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 9, name: "Egg Tamata", nameTe: "గుడ్డు టమాట", price: 130, veg: false, status: "Active", weeklyDishInd: false },
    { id: 10, name: "Omlete", nameTe: "ఆమ్లెట్", price: 60, veg: false, status: "Active", weeklyDishInd: false }
  ],
  "non-veg-starter": [
    { id: 11, name: "Chicken 65", nameTe: "చికెన్ 65", price: 260, veg: false, top: true, status: "Active", weeklyDishInd: false },
    { id: 12, name: "Chicken Bone Fry", nameTe: "చికెన్ బోన్ ఫ్రై", price: 180, veg: false, status: "Active", weeklyDishInd: false },
    { id: 13, name: "Chicken Bone Roast", nameTe: "చికెన్ బోన్ రోస్ట్", price: 200, veg: false, status: "Active", weeklyDishInd: false },
    { id: 14, name: "Chicken Boneless Fry", nameTe: "చికెన్ బోన్‌లెస్ ఫ్రై", price: 230, veg: false, status: "Active", weeklyDishInd: false },
    { id: 15, name: "Chicken Boneless Roast", nameTe: "చికెన్ బోన్‌లెస్ రోస్ట్", price: 240, veg: false, status: "Active", weeklyDishInd: false },
    { id: 16, name: "Chicken Manchuria", nameTe: "చికెన్ మంచూరియా", price: 260, veg: false, status: "Active", weeklyDishInd: false },
    { id: 17, name: "Chili Chicken", nameTe: "చిల్లీ చికెన్", price: 210, veg: false, status: "Active", weeklyDishInd: false },
    { id: 18, name: "Lemon Chicken", nameTe: "లెమన్ చికెన్", price: 260, veg: false, thumb: "images/menu/lemon-chicken-100.jpg", photo: "images/menu/lemon-chicken-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 19, name: "Lollipop Fry", nameTe: "లాలీపాప్ ఫ్రై", price: 260, veg: false, thumb: "images/menu/lollipop-fry-100.jpg", photo: "images/menu/lollipop-fry-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 20, name: "Lollipop Roast", nameTe: "లాలీపాప్ రోస్ట్", price: 280, veg: false, thumb: "images/menu/lollipop-roast-100.jpg", photo: "images/menu/lollipop-roast-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 21, name: "Pepper Chicken", nameTe: "పెప్పర్ చికెన్", price: 240, veg: false, status: "Active", weeklyDishInd: false },
    { id: 22, name: "Tiger Chicken", nameTe: "టైగర్ చికెన్", price: 280, veg: false, thumb: "images/menu/tiger-chicken-100.jpg", photo: "images/menu/tiger-chicken-500.jpg", status: "Active", weeklyDishInd: false }
  ],
  "veg-curries": [
    { id: 23, name: "Batani Curry", nameTe: "బటానీ కర్రీ", price: 110, veg: true, status: "Active", weeklyDishInd: false },
    { id: 24, name: "Dal Curry", nameTe: "దాల్ కర్రీ", price: 110, veg: true, status: "Active", weeklyDishInd: false },
    { id: 25, name: "Dal Tadka", nameTe: "దాల్ తడ్కా", price: 130, veg: true, thumb: "images/menu/dal-tadka-100.jpg", photo: "images/menu/dal-tadka-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 26, name: "Kaju Curry", nameTe: "కాజు కర్రీ", price: 200, veg: true, status: "Active", weeklyDishInd: false },
    { id: 27, name: "Kaju Paneer", nameTe: "కాజు పనీర్", price: 220, veg: true, status: "Active", weeklyDishInd: false },
    { id: 28, name: "Kaju Tamata", nameTe: "కాజు టమాట", price: 170, veg: true, status: "Active", weeklyDishInd: false },
    { id: 29, name: "Methi Chaman", nameTe: "మేథీ చమన్", price: 200, veg: true, status: "Active", weeklyDishInd: false },
    { id: 30, name: "Mushroom Curry", nameTe: "మష్రూమ్ కర్రీ", price: 170, veg: true, status: "Active", weeklyDishInd: false },
    { id: 31, name: "Palak Curry", nameTe: "పాలక్ కర్రీ", price: 110, veg: true, status: "Active", weeklyDishInd: false },
    { id: 32, name: "Palak Paneer", nameTe: "పాలక్ పనీర్", price: 170, veg: true, status: "Active", weeklyDishInd: false },
    { id: 33, name: "Paneer Butter Masala", nameTe: "పనీర్ బటర్ మసాలా", price: 190, veg: true, top: true, status: "Active", weeklyDishInd: false },
    { id: 34, name: "Tamata Curry", nameTe: "టమాట కర్రీ", price: 110, veg: true, status: "Active", weeklyDishInd: false },
    { id: 35, name: "Veg Mix Curry", nameTe: "వెజ్ మిక్స్ కర్రీ", price: 130, veg: true, status: "Active", weeklyDishInd: false }
  ],
  "veg-starters": [
    { id: 36, name: "Alasandha Fry", nameTe: "అలసంద ఫ్రై", price: 130, veg: true, status: "Active", weeklyDishInd: false },
    { id: 37, name: "Batani Fry", nameTe: "బటానీ ఫ్రై", price: 130, veg: true, thumb: "images/menu/batani-fry-100.jpg", photo: "images/menu/batani-fry-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 38, name: "Batani Roast", nameTe: "బటానీ రోస్ట్", price: 130, veg: true, thumb: "images/menu/batani-roast-100.jpg", photo: "images/menu/batani-roast-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 39, name: "Chena Fry", nameTe: "చేన ఫ్రై", price: 130, veg: true, thumb: "images/menu/chena-fry-100.jpg", photo: "images/menu/chena-fry-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 40, name: "Gobi Fry", nameTe: "గోబీ ఫ్రై", price: 130, veg: true, thumb: "images/menu/gobi-fry-100.jpg", photo: "images/menu/gobi-fry-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 41, name: "Gobi Manchuria", nameTe: "గోబీ మంచూరియా", price: 150, veg: true, thumb: "images/menu/gobi-manchuria-100.jpg", photo: "images/menu/gobi-manchuria-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 42, name: "Groundnut Masala", nameTe: "వేరుశనగ మసాలా", price: 140, veg: true, thumb: "images/menu/groundnut-masala-100.jpg", photo: "images/menu/groundnut-masala-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 43, name: "Kaju Fry", nameTe: "కాజు ఫ్రై", price: 250, veg: true, status: "Active", weeklyDishInd: false },
    { id: 44, name: "Kaju Roast", nameTe: "కాజు రోస్ట్", price: 250, veg: true, status: "Active", weeklyDishInd: false },
    { id: 45, name: "Mushroom Chili", nameTe: "మష్రూమ్ చిల్లీ", price: 190, veg: true, thumb: "images/menu/mushroom-chili-100.jpg", photo: "images/menu/mushroom-chili-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 46, name: "Mushroom Fry", nameTe: "మష్రూమ్ ఫ్రై", price: 170, veg: true, thumb: "images/menu/mushroom-fry-100.jpg", photo: "images/menu/mushroom-fry-500.jpg", status: "Active", weeklyDishInd: false },
    { id: 47, name: "Mushroom Manchuria", nameTe: "మష్రూమ్ మంచూరియా", price: 190, veg: true, status: "Active", weeklyDishInd: false },
    { id: 48, name: "Mushroom Pepper", nameTe: "మష్రూమ్ పెప్పర్", price: 190, veg: true, status: "Active", weeklyDishInd: false },
    { id: 49, name: "Onion Pakodi", nameTe: "ఉల్లి పకోడి", price: 130, veg: true, status: "Active", weeklyDishInd: false },
    { id: 50, name: "Paneer 65", nameTe: "పనీర్ 65", price: 200, veg: true, status: "Active", weeklyDishInd: false },
    { id: 51, name: "Paneer Chilli", nameTe: "పనీర్ చిల్లీ", price: 210, veg: true, status: "Active", weeklyDishInd: false },
    { id: 52, name: "Paneer Fry", nameTe: "పనీర్ ఫ్రై", price: 190, veg: true, status: "Active", weeklyDishInd: false },
    { id: 53, name: "Paneer Manchuria", nameTe: "పనీర్ మంచూరియా", price: 210, veg: true, status: "Active", weeklyDishInd: false }
  ],
  "biryani": [
    { id: 54, name: "Dum Biryani", nameTe: "దమ్ బిర్యానీ", price: 170, veg: false, top: true, status: "Active", weeklyDishInd: false },
    { id: 55, name: "Fry Biryani", nameTe: "ఫ్రై బిర్యానీ", price: 180, veg: false, status: "Active", weeklyDishInd: false },
    { id: 56, name: "Mutton Fry Biryani", nameTe: "మటన్ ఫ్రై బిర్యానీ", price: 360, veg: false, status: "Active", weeklyDishInd: false },
    { id: 57, name: "Natukodi Fry Biryani", nameTe: "నాటుకోడి ఫ్రై బిర్యానీ", price: 310, veg: false, status: "Active", weeklyDishInd: false },
    { id: 58, name: "Prawns Fry Biryani", nameTe: "రొయ్యల ఫ్రై బిర్యానీ", price: 320, veg: false, status: "Active", weeklyDishInd: false },
    { id: 59, name: "SP Biryani", nameTe: "SP బిర్యానీ", price: 220, veg: false, status: "Active", weeklyDishInd: false }
  ],
  "roti": [
    { id: 60, name: "Katak Roti", nameTe: "కటక్ రొట్టె", price: 10, veg: true, status: "Active", weeklyDishInd: false },
    { id: 61, name: "Patala Roti", nameTe: "పాతల రొట్టె", price: 10, veg: true, status: "Active", weeklyDishInd: false },
    { id: 62, name: "Ponga Roti", nameTe: "పొంగా రొట్టె", price: 12, veg: true, status: "Active", weeklyDishInd: false }
  ],
  "fried-rice": [
    { id: 63, name: "Chicken Rice", nameTe: "చికెన్ రైస్", price: 130, veg: false, status: "Active", weeklyDishInd: false },
    { id: 64, name: "Curd Rice", nameTe: "పెరుగు అన్నం", price: 80, veg: true, status: "Active", weeklyDishInd: false },
    { id: 65, name: "Egg Rice", nameTe: "గుడ్డు రైస్", price: 110, veg: false, status: "Active", weeklyDishInd: false },
    { id: 66, name: "Gobi Rice", nameTe: "గోబీ రైస్", price: 130, veg: true, status: "Active", weeklyDishInd: false },
    { id: 67, name: "Jeera Rice", nameTe: "జీరా రైస్", price: 130, veg: true, status: "Active", weeklyDishInd: false },
    { id: 68, name: "Kaju Rice", nameTe: "కాజు రైస్", price: 180, veg: true, status: "Active", weeklyDishInd: false },
    { id: 69, name: "Mushroom Rice", nameTe: "మష్రూమ్ రైస్", price: 150, veg: true, status: "Active", weeklyDishInd: false },
    { id: 70, name: "Paneer Rice", nameTe: "పనీర్ రైస్", price: 170, veg: true, status: "Active", weeklyDishInd: false },
    { id: 71, name: "Plain White Rice", nameTe: "ప్లెయిన్ వైట్ రైస్", price: 60, veg: true, status: "Active", weeklyDishInd: false },
    { id: 72, name: "Veg Rice", nameTe: "వెజ్ రైస్", price: 120, veg: true, status: "Active", weeklyDishInd: false }
  ],
  "chicken-curries": [
    { id: 73, name: "Andhra Chicken", nameTe: "ఆంధ్రా చికెన్", price: 360, veg: false, status: "Active", weeklyDishInd: false },
    { id: 74, name: "Bonda Chicken", nameTe: "బొండా చికెన్", price: 410, veg: false, status: "Active", weeklyDishInd: false },
    { id: 75, name: "Butter Chicken", nameTe: "బటర్ చికెన్", price: 260, veg: false, top: true, status: "Active", weeklyDishInd: false },
    { id: 76, name: "Chicken Bone Curry", nameTe: "చికెన్ బోన్ కర్రీ", price: 180, veg: false, status: "Active", weeklyDishInd: false },
    { id: 77, name: "Chicken Boneless Curry", nameTe: "చికెన్ బోన్‌లెస్ కర్రీ", price: 240, veg: false, status: "Active", weeklyDishInd: false },
    { id: 78, name: "Fish Curry (2 pc)", nameTe: "చేప కర్రీ (2 ముక్కలు)", price: 140, veg: false, status: "Active", weeklyDishInd: false },
    { id: 79, name: "Fish Fry (2 pc)", nameTe: "చేప ఫ్రై (2 ముక్కలు)", price: 140, veg: false, status: "Active", weeklyDishInd: false },
    { id: 80, name: "Kadai Chicken", nameTe: "కడాయి చికెన్", price: 270, veg: false, status: "Active", weeklyDishInd: false },
    { id: 81, name: "Kaju Chicken", nameTe: "కాజు చికెన్", price: 290, veg: false, status: "Active", weeklyDishInd: false },
    { id: 82, name: "Lollipop Curry", nameTe: "లాలీపాప్ కర్రీ", price: 260, veg: false, status: "Active", weeklyDishInd: false },
    { id: 83, name: "Mughlai Chicken", nameTe: "మొఘలై చికెన్", price: 280, veg: false, status: "Active", weeklyDishInd: false },
    { id: 84, name: "Mutton Curry", nameTe: "మటన్ కర్రీ", price: 330, veg: false, status: "Active", weeklyDishInd: false },
    { id: 85, name: "Mutton Fry", nameTe: "మటన్ ఫ్రై", price: 360, veg: false, status: "Active", weeklyDishInd: false },
    { id: 86, name: "Natukodi Curry", nameTe: "నాటుకోడి కర్రీ", price: 310, veg: false, status: "Active", weeklyDishInd: false },
    { id: 87, name: "Natukodi Fry", nameTe: "నాటుకోడి ఫ్రై", price: 310, veg: false, status: "Active", weeklyDishInd: false },
    { id: 88, name: "Nellore Chicken", nameTe: "నెల్లూరు చికెన్", price: 360, veg: false, status: "Active", weeklyDishInd: false },
    { id: 89, name: "Panjabi Chicken", nameTe: "పంజాబీ చికెన్", price: 280, veg: false, status: "Active", weeklyDishInd: false },
    { id: 90, name: "Prawns Curry", nameTe: "రొయ్యల కర్రీ", price: 280, veg: false, status: "Active", weeklyDishInd: false },
    { id: 91, name: "Prawns Fry", nameTe: "రొయ్యల ఫ్రై", price: 290, veg: false, status: "Active", weeklyDishInd: false },
    { id: 92, name: "Rambha Chicken", nameTe: "రంభా చికెన్", price: 280, veg: false, status: "Active", weeklyDishInd: false },
    { id: 93, name: "Star Chicken", nameTe: "స్టార్ చికెన్", price: 260, veg: false, status: "Active", weeklyDishInd: false }
  ],
  "specials": [
    { id: 94, name: "Badam Milk", nameTe: "బాదం మిల్క్", price: 60, veg: true, status: "Active", weeklyDishInd: false },
    { id: 95, name: "Cool Drinks", nameTe: "కూల్ డ్రింక్స్", price: null, veg: true, thumb: "images/menu/cool-drinks-100.jpg", photo: "images/menu/cool-drinks-500.jpg", top: false, status: "Active", weeklyDishInd: false },
    { id: 96, name: "Ice Cream", nameTe: "ఐస్ క్రీం", price: null, veg: true, thumb: "images/menu/ice-cream-100.jpg", photo: "images/menu/ice-cream-500.jpg", top: false, status: "Active", weeklyDishInd: false },
    { id: 97, name: "Kheer", nameTe: "ఖీర్", price: 50, veg: true, status: "Active", weeklyDishInd: false },
    { id: 98, name: "Tea", nameTe: "టీ", price: 20, veg: true, status: "Active", weeklyDishInd: false },
    { id: 99, name: "Coffee", nameTe: "కాఫీ", price: 20, veg: true, status: "Active", weeklyDishInd: false }
  ]
};

/* Category display order, titles and icons — shared by the printed menu and the order app. */
var CATEGORY_META = [
  { id: "egg-curries", title: "Egg Curries", titleTe: "గుడ్డు కూరలు", short: "Egg Curries", shortTe: "గుడ్డు కూరలు",
    image: "images/menu/categories/egg-curries.jpg",
    icon: '<path d="M32 8C20 8 12 26 12 38a20 20 0 0040 0C52 26 44 8 32 8z"/>' },
  { id: "non-veg-starter", title: "Non-Veg Starter", titleTe: "నాన్-వెజ్ స్టార్టర్", short: "Starters", shortTe: "స్టార్టర్స్",
    icon: '<path d="M12 52L52 12"/><circle cx="24" cy="40" r="7"/><circle cx="34" cy="30" r="7"/><circle cx="44" cy="20" r="7"/>' },
  { id: "veg-curries", title: "Veg Curries", titleTe: "వెజ్ కూరలు", short: "Veg Curries", shortTe: "వెజ్ కూరలు",
    icon: '<path d="M10 32h44a22 22 0 01-44 0z"/><path d="M24 30c0-6 2-9 2-9M32 30c0-8 3-11 3-11M40 30c0-6 2-9 2-9"/>' },
  { id: "veg-starters", title: "Veg Starters", titleTe: "వెజ్ స్టార్టర్స్", short: "Veg Starters", shortTe: "వెజ్ స్టార్టర్స్",
    icon: '<path d="M32 6c6 10-4 12-4 20 0 4 3 7 7 7s8-4 8-9c6 4 9 11 9 17 0 13-11 23-24 23S8 54 8 41c0-9 5-16 9-21 2 8 7 10 7 10-2-9 2-16 8-24z"/>' },
  { id: "biryani", title: "Biryani", titleTe: "బిర్యానీ", short: "Biryani", shortTe: "బిర్యానీ",
    icon: '<path d="M14 30h36l-3 20a6 6 0 01-6 5H23a6 6 0 01-6-5z"/><path d="M10 30h44"/><path d="M22 30v-8a10 10 0 0120 0v8"/><circle cx="32" cy="12" r="3"/>' },
  { id: "roti", title: "Roti", titleTe: "రొట్టె", short: "Roti", shortTe: "రొట్టె",
    icon: '<circle cx="32" cy="32" r="21"/><path d="M32 15v10M32 39v10M15 32h10M39 32h10M21 21l7 7M36 36l7 7M43 21l-7 7M28 36l-7 7"/>' },
  { id: "fried-rice", title: "Fried Rice", titleTe: "ఫ్రైడ్ రైస్", short: "Fried Rice", shortTe: "ఫ్రైడ్ రైస్",
    icon: '<path d="M10 32h44a22 22 0 01-44 0z"/><circle cx="24" cy="25" r="1.6" fill="currentColor" stroke="none"/><circle cx="32" cy="21" r="1.6" fill="currentColor" stroke="none"/><circle cx="40" cy="25" r="1.6" fill="currentColor" stroke="none"/><circle cx="28" cy="29" r="1.6" fill="currentColor" stroke="none"/><circle cx="36" cy="29" r="1.6" fill="currentColor" stroke="none"/>' },
  { id: "chicken-curries", title: "Chicken, Mutton & Seafood Curries", titleTe: "చికెన్, మటన్ & సీఫుడ్ కూరలు", short: "Chicken & Mutton", shortTe: "చికెన్ & మటన్",
    icon: '<path d="M8 32c10-11 25-15 36-8 4 2.5 7 5.5 9 8-2 2.5-5 5.5-9 8-11 7-26 3-36-8z"/><path d="M44 32l12-9v18z"/><circle cx="18" cy="29" r="1.8" fill="currentColor" stroke="none"/>' },
  { id: "specials", title: "Navrang Specials", titleTe: "నవ్రంగ్ స్పెషల్స్", short: "Specials", shortTe: "స్పెషల్స్",
    icon: '<path d="M32 6l7 16 17 2-13 12 4 18-15-9-15 9 4-18-13-12 17-2z"/>' }
];
