/* Navrang menu data — edit prices/items here; the page renders from this object. */
var MENU_DATA = {
  "egg-curries": [
    { name: "Egg Burji", nameTe: "గుడ్డు బుర్జీ", price: 110, veg: false, thumb: "images/menu/egg-burji-100.jpg", photo: "images/menu/egg-burji-500.jpg", top: true },
    { name: "Egg Keema", nameTe: "గుడ్డు కీమా", price: 110, veg: false, thumb: "images/menu/egg-keema-100.jpg", photo: "images/menu/egg-keema-500.jpg" },
    { name: "Egg Curry", nameTe: "గుడ్డు కర్రీ", price: 110, veg: false, thumb: "images/menu/egg-currey-100.jpg", photo: "images/menu/egg-currey-500.jpg" },
    { name: "Egg Fry", nameTe: "గుడ్డు ఫ్రై", price: 130, veg: false },
    { name: "Egg Roast", nameTe: "గుడ్డు రోస్ట్", price: 130, veg: false },
    { name: "Egg Chilli", nameTe: "గుడ్డు చిల్లీ", price: 130, veg: false },
    { name: "Egg Dal", nameTe: "గుడ్డు దాల్", price: 130, veg: false },
    { name: "Egg Tamata", nameTe: "గుడ్డు టమాట", price: 130, veg: false },
    { name: "Omlete", nameTe: "ఆమ్లెట్", price: 70, veg: false },
    { name: "Egg Manchuria", nameTe: "గుడ్డు మంచూరియా", price: 140, veg: false }
  ],
  "non-veg-starter": [
    { name: "Chicken Bone Fry", nameTe: "చికెన్ బోన్ ఫ్రై", price: 190, veg: false },
    { name: "Chicken Bone Roast", nameTe: "చికెన్ బోన్ రోస్ట్", price: 210, veg: false },
    { name: "Chicken Boneless Fry", nameTe: "చికెన్ బోన్‌లెస్ ఫ్రై", price: 240, veg: false },
    { name: "Chicken Boneless Roast", nameTe: "చికెన్ బోన్‌లెస్ రోస్ట్", price: 240, veg: false },
    { name: "Chili Chicken", nameTe: "చిల్లీ చికెన్", price: 210, veg: false },
    { name: "Pepper Chicken", nameTe: "పెప్పర్ చికెన్", price: 240, veg: false },
    { name: "Chicken 65", nameTe: "చికెన్ 65", price: 260, veg: false, top: true },
    { name: "Chicken Manchuria", nameTe: "చికెన్ మంచూరియా", price: 260, veg: false },
    { name: "Lollipop Roast", nameTe: "లాలీపాప్ రోస్ట్", price: 260, veg: false },
    { name: "Lollipop Fry", nameTe: "లాలీపాప్ ఫ్రై", price: 260, veg: false },
    { name: "Tiger Chicken", nameTe: "టైగర్ చికెన్", price: 280, veg: false },
    { name: "Lemon Chicken", nameTe: "లెమన్ చికెన్", price: 260, veg: false }
  ],
  "veg-curries": [
    { name: "Tamata Curry", nameTe: "టమాట కర్రీ", price: 110, veg: true },
    { name: "Dal Curry", nameTe: "దాల్ కర్రీ", price: 110, veg: true },
    { name: "Batani Curry", nameTe: "బటానీ కర్రీ", price: 110, veg: true },
    { name: "Palak Curry", nameTe: "పాలక్ కర్రీ", price: 110, veg: true },
    { name: "Dal Tadka", nameTe: "దాల్ తడ్కా", price: 130, veg: true },
    { name: "Veg Mix Curry", nameTe: "వెజ్ మిక్స్ కర్రీ", price: 130, veg: true },
    { name: "Mushroom Curry", nameTe: "మష్రూమ్ కర్రీ", price: 160, veg: true },
    { name: "Paneer Butter Masala", nameTe: "పనీర్ బటర్ మసాలా", price: 190, veg: true, top: true },
    { name: "Palak Paneer", nameTe: "పాలక్ పనీర్", price: 170, veg: true },
    { name: "Kaju Tamata", nameTe: "కాజు టమాట", price: 170, veg: true },
    { name: "Kaju Curry", nameTe: "కాజు కర్రీ", price: 190, veg: true },
    { name: "Methi Chaman", nameTe: "మేథీ చమన్", price: 190, veg: true },
    { name: "Kaju Paneer", nameTe: "కాజు పనీర్", price: 210, veg: true }
  ],
  "veg-starters": [
    { name: "Batani Fry", nameTe: "బటానీ ఫ్రై", price: 130, veg: true },
    { name: "Batani Roast", nameTe: "బటానీ రోస్ట్", price: 130, veg: true },
    { name: "Groundnut Masala", nameTe: "వేరుశనగ మసాలా", price: 130, veg: true },
    { name: "Chena Fry", nameTe: "చేన ఫ్రై", price: 130, veg: true },
    { name: "Gobi Fry", nameTe: "గోబీ ఫ్రై", price: 130, veg: true },
    { name: "Gobi Manchuria", nameTe: "గోబీ మంచూరియా", price: 150, veg: true },
    { name: "Onion Pakodi", nameTe: "ఉల్లి పకోడి", price: 130, veg: true },
    { name: "Mushroom Fry", nameTe: "మష్రూమ్ ఫ్రై", price: 160, veg: true },
    { name: "Mushroom Chili", nameTe: "మష్రూమ్ చిల్లీ", price: 170, veg: true },
    { name: "Paneer Fry", nameTe: "పనీర్ ఫ్రై", price: 190, veg: true },
    { name: "Kaju Fry", nameTe: "కాజు ఫ్రై", price: 240, veg: true },
    { name: "Kaju Roast", nameTe: "కాజు రోస్ట్", price: 240, veg: true },
    { name: "Alasandha Fry", nameTe: "అలసంద ఫ్రై", price: 130, veg: true },
    { name: "Paneer Manchuria", nameTe: "పనీర్ మంచూరియా", price: 210, veg: true },
    { name: "Paneer 65", nameTe: "పనీర్ 65", price: 190, veg: true },
    { name: "Paneer Chilli", nameTe: "పనీర్ చిల్లీ", price: 210, veg: true },
    { name: "Mushroom Manchuria", nameTe: "మష్రూమ్ మంచూరియా", price: 160, veg: true },
    { name: "Mushroom Pepper", nameTe: "మష్రూమ్ పెప్పర్", price: 170, veg: true }
  ],
  "biryani": [
    { name: "Dum Biryani", nameTe: "దమ్ బిర్యానీ", price: 160, veg: false, top: true },
    { name: "Fry Biryani", nameTe: "ఫ్రై బిర్యానీ", price: 180, veg: false },
    { name: "SP Biryani", nameTe: "SP బిర్యానీ", price: 210, veg: false },
    { name: "Mutton Fry Biryani", nameTe: "మటన్ ఫ్రై బిర్యానీ", price: 360, veg: false },
    { name: "Natukodi Fry Biryani", nameTe: "నాటుకోడి ఫ్రై బిర్యానీ", price: 310, veg: false },
    { name: "Prawns Fry Biryani", nameTe: "రొయ్యల ఫ్రై బిర్యానీ", price: 310, veg: false }
  ],
  "roti": [
    { name: "Ponga Roti", nameTe: "పొంగా రొట్టె", price: 18, veg: true },
    { name: "Patala Roti", nameTe: "పాతల రొట్టె", price: 17, veg: true },
    { name: "Katak Roti", nameTe: "కటక్ రొట్టె", price: 17, veg: true }
  ],
  "fried-rice": [
    { name: "Egg Rice", nameTe: "గుడ్డు రైస్", price: 110, veg: false },
    { name: "Veg Rice", nameTe: "వెజ్ రైస్", price: 110, veg: true },
    { name: "Chicken Rice", nameTe: "చికెన్ రైస్", price: 130, veg: false },
    { name: "Jeera Rice", nameTe: "జీరా రైస్", price: 130, veg: true },
    { name: "Gobi Rice", nameTe: "గోబీ రైస్", price: 130, veg: true },
    { name: "Mushroom Rice", nameTe: "మష్రూమ్ రైస్", price: 140, veg: true },
    { name: "Kaju Rice", nameTe: "కాజు రైస్", price: 170, veg: true },
    { name: "Paneer Rice", nameTe: "పనీర్ రైస్", price: 170, veg: true },
    { name: "Plain White Rice", nameTe: "ప్లెయిన్ వైట్ రైస్", price: 60, veg: true },
    { name: "Curd Rice", nameTe: "పెరుగు అన్నం", price: 70, veg: true }
  ],
  "chicken-curries": [
    { name: "Chicken Bone Curry", nameTe: "చికెన్ బోన్ కర్రీ", price: 180, veg: false },
    { name: "Chicken Boneless Curry", nameTe: "చికెన్ బోన్‌లెస్ కర్రీ", price: 240, veg: false },
    { name: "Butter Chicken", nameTe: "బటర్ చికెన్", price: 260, veg: false, top: true },
    { name: "Kadai Chicken", nameTe: "కడాయి చికెన్", price: 270, veg: false },
    { name: "Kaju Chicken", nameTe: "కాజు చికెన్", price: 280, veg: false },
    { name: "Mughlai Chicken", nameTe: "మొఘలై చికెన్", price: 280, veg: false },
    { name: "Lollipop Curry", nameTe: "లాలీపాప్ కర్రీ", price: 260, veg: false },
    { name: "Rambha Chicken", nameTe: "రంభా చికెన్", price: 280, veg: false },
    { name: "Panjabi Chicken", nameTe: "పంజాబీ చికెన్", price: 280, veg: false },
    { name: "Andhra Chicken", nameTe: "ఆంధ్రా చికెన్", price: 360, veg: false },
    { name: "Nellore Chicken", nameTe: "నెల్లూరు చికెన్", price: 360, veg: false },
    { name: "Bonda Chicken", nameTe: "బొండా చికెన్", price: 410, veg: false },
    { name: "Star Chicken", nameTe: "స్టార్ చికెన్", price: 260, veg: false },
    { name: "Fish Curry (2 pc)", nameTe: "చేప కర్రీ (2 ముక్కలు)", price: 140, veg: false },
    { name: "Fish Fry (2 pc)", nameTe: "చేప ఫ్రై (2 ముక్కలు)", price: 140, veg: false },
    { name: "Prawns Curry", nameTe: "రొయ్యల కర్రీ", price: 280, veg: false },
    { name: "Prawns Fry", nameTe: "రొయ్యల ఫ్రై", price: 290, veg: false },
    { name: "Natukodi Curry", nameTe: "నాటుకోడి కర్రీ", price: 310, veg: false },
    { name: "Natukodi Fry", nameTe: "నాటుకోడి ఫ్రై", price: 310, veg: false },
    { name: "Mutton Curry", nameTe: "మటన్ కర్రీ", price: 330, veg: false },
    { name: "Mutton Fry", nameTe: "మటన్ ఫ్రై", price: 360, veg: false },
    { name: "Crab Curry", nameTe: "పీత కర్రీ", price: 210, veg: false },
    { name: "Crab Roast", nameTe: "పీత రోస్ట్", price: 210, veg: false },
    { name: "Kamju Curry (2 pc)", nameTe: "కంజు కర్రీ (2 ముక్కలు)", price: 250, veg: false },
    { name: "Kamju Roast (2 pc)", nameTe: "కంజు రోస్ట్ (2 ముక్కలు)", price: 260, veg: false }
  ],
  "specials": [
    { name: "Tea/Coffee", nameTe: "టీ/కాఫీ", price: 20, veg: true },
    { name: "Kheer", nameTe: "ఖీర్", price: 60, veg: true },
    { name: "Badam Milk", nameTe: "బాదం మిల్క్", price: 60, veg: true },
    { name: "Ice Cream", nameTe: "ఐస్ క్రీం", price: null, veg: true },
    { name: "Cool Drinks", nameTe: "కూల్ డ్రింక్స్", price: null, veg: true }
  ]
};

/* Category display order, titles and icons — shared by the printed menu and the order app. */
var CATEGORY_META = [
  { id: "egg-curries", title: "Egg Curries", titleTe: "గుడ్డు కూరలు", short: "Egg Curries", shortTe: "గుడ్డు కూరలు",
    image: "images/menu/categories/egg-curries.jpg",
    icon: '<path d="M32 8C20 8 12 26 12 38a20 20 0 0040 0C52 26 44 8 32 8z"/>' },
  { id: "non-veg-starter", title: "Non-Veg Starter", titleTe: "నాన్-వెజ్ స్టార్టర్", short: "Starters", shortTe: "స్టార్టర్స్",
    icon: '<path d="M12 52L52 12"/><circle cx="24" cy="40" r="7"/><circle cx="34" cy="30" r="7"/><circle cx="44" cy="20" r="7"/>' },
  { id: "veg-curries", title: "Veg Curries", titleTe: "వెజ్ కూరలు", short: "Veg Curries", shortTe: "వెజ్ కూరలు",
    icon: '<path d="M10 32h44a22 22 0 01-44 0z"/><path d="M24 30c0-6 2-9 2-9M32 30c0-8 3-11 3-11M40 30c0-6 2-9 2-9"/>' },
  { id: "veg-starters", title: "Veg Starters", titleTe: "వెజ్ స్టార్టర్స్", short: "Veg Starters", shortTe: "వెజ్ స్టార్టర్స్",
    icon: '<path d="M32 6c6 10-4 12-4 20 0 4 3 7 7 7s8-4 8-9c6 4 9 11 9 17 0 13-11 23-24 23S8 54 8 41c0-9 5-16 9-21 2 8 7 10 7 10-2-9 2-16 8-24z"/>' },
  { id: "biryani", title: "Biryani", titleTe: "బిర్యానీ", short: "Biryani", shortTe: "బిర్యానీ",
    icon: '<path d="M14 30h36l-3 20a6 6 0 01-6 5H23a6 6 0 01-6-5z"/><path d="M10 30h44"/><path d="M22 30v-8a10 10 0 0120 0v8"/><circle cx="32" cy="12" r="3"/>' },
  { id: "roti", title: "Roti", titleTe: "రొట్టె", short: "Roti", shortTe: "రొట్టె",
    icon: '<circle cx="32" cy="32" r="21"/><path d="M32 15v10M32 39v10M15 32h10M39 32h10M21 21l7 7M36 36l7 7M43 21l-7 7M28 36l-7 7"/>' },
  { id: "fried-rice", title: "Fried Rice", titleTe: "ఫ్రైడ్ రైస్", short: "Fried Rice", shortTe: "ఫ్రైడ్ రైస్",
    icon: '<path d="M10 32h44a22 22 0 01-44 0z"/><circle cx="24" cy="25" r="1.6" fill="currentColor" stroke="none"/><circle cx="32" cy="21" r="1.6" fill="currentColor" stroke="none"/><circle cx="40" cy="25" r="1.6" fill="currentColor" stroke="none"/><circle cx="28" cy="29" r="1.6" fill="currentColor" stroke="none"/><circle cx="36" cy="29" r="1.6" fill="currentColor" stroke="none"/>' },
  { id: "chicken-curries", title: "Chicken, Mutton & Seafood Curries", titleTe: "చికెన్, మటన్ & సీఫుడ్ కూరలు", short: "Chicken & Mutton", shortTe: "చికెన్ & మటన్",
    icon: '<path d="M8 32c10-11 25-15 36-8 4 2.5 7 5.5 9 8-2 2.5-5 5.5-9 8-11 7-26 3-36-8z"/><path d="M44 32l12-9v18z"/><circle cx="18" cy="29" r="1.8" fill="currentColor" stroke="none"/>' },
  { id: "specials", title: "Navrang Specials", titleTe: "నవ్రంగ్ స్పెషల్స్", short: "Specials", shortTe: "స్పెషల్స్",
    icon: '<path d="M32 6l7 16 17 2-13 12 4 18-15-9-15 9 4-18-13-12 17-2z"/>' }
];
